### ISSUE TITLE
Faire des modifications du support via AUS

### ISSUE THREAD

**Issue by PtiGourou26** [InseeFrLab/formation-bonnes-pratiques-git-R#4]
Bonjour à tous les deux,

Dans le cadre, de la formation que nous allons donner à Lyon, je souhaiterais modifier, réordonner, supprimer des slides (à la marge). J'ai copié le zip sur mon poste et ouvert sous AUS, j'ai essayé de render le document `formation_light.qmd` mais j'ai une erreur sur l'extension onyxia :

```r 
ERROR: Unable to read the extension 'onyxia'.
Please ensure that you provided the correct id and that the extension is installed.

Error: Unable to read the extension 'onyxia'.
Please ensure that you provided the correct id and that the extension is installed.
    at loadExtension (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:59393:15)
    at Object.extension (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:59292:34)
    at readExtensionFormat (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:83227:50)
    at resolveFormats (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:83173:41)
    at async renderContexts (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:82635:21)
    at async Object.renderFormats (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:82686:26)
    at async inputTargetIndex (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:83502:21)
    at async resolveInputTarget (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:83581:19)
    at async resolveItem (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:93624:26)
    at async navigationItem (file:///C:/PROGRA~1/RStudio/RESOUR~1/app/bin/quarto/bin/quarto.js:93595:16)
```

Au delà de cette erreur, est-ce que le projet pourra facilement tourner sur AUS ou ça va être compliqué ? Je dois utiliser le DataLab ?

Merci,

Rémi ALBERT

**Comment by avouacr** [comment]
Salut Rémi, difficile à dire, on a jamais testé le render de la formation sur AUS. En tout cas, le projet est censé être auto-contenu (l'extension Onyxia est bien présente, ici : https://github.com/InseeFrLab/formation-bonnes-pratiques-git-R/tree/main/slides/_extensions/InseeFrLab/onyxia). Y'a pas mal de choses qui peuvent rentrer en compte, je ne sais pas si la version de quarto est à jour, etc.

Bref, c'est certain que ça sera beaucoup plus simple de faire tes modifs de la formation sur le datalab. Ca on a l'habitude, donc on sait que ça marche :)

**Comment by PtiGourou26** [comment]
Merci Romain pour ta réponse, je vais passer par le datalab dans ce cas !
